# Mkdocs configuration file. See https://www.mkdocs.org/user-guide/configuration/

site_name: oncvpsp docs
site_url: https://oncvpsp.github.io/oncvpsp/
site_description: Oncvpsp documentation
site_author: The Oncvpspt group
docs_dir: doc

repo_name: github-oncvpsp
repo_url: https://github.com/oncvpsp/oncvpsp
edit_uri: edit/master/doc/

nav:
    - Users Guide: users_guide.md
    - Ghosts: ghosts.md
    - Core correction: core_correction.md
    - Relativistic : relativistic.md
    - Program Overview: program_overview.md
    - Libxc Use: libxc_use.md
    - Coding Standards: coding_standards.md
    - Pwscf Exc: pwscf_exc.md
    - Release Notes: release_notes.md

theme:
    name: material
    #logo: images/logo-oncvpsp.png
    #favicon: images/favicon.ico
    #palette:
    #    primary: deep orange
    #    accent: deep orange
    features:
      - navigation.tabs
      #- toc.integrate
      - header.autohide

# The section below activates markdown/theme extensions and other parameters related to
# the HTML/JS website. Play with it only if you know what you're doing!

markdown_extensions:
#  - markdown.extensions.meta
  - markdown.extensions.toc:
        permalink: true  # For ¶
  - markdown.extensions.admonition
  - markdown.extensions.fenced_code
  - markdown.extensions.codehilite
  - markdown.extensions.smarty
  - markdown.extensions.tables
  - markdown.extensions.def_list
  - markdown.extensions.sane_lists
  - markdown.extensions.attr_list
  - pymdownx.arithmatex:
        generic: true
        #inline_syntax: ['dollar']
        #block_syntax:  ['dollar', 'begin']
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  #- pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  #- pymdownx.highlight:
  #    anchor_linenums: true
  #    line_spans: __span
  #    pygments_lang_class: true
  #- pymdownx.snippets
  - pymdownx.smartsymbols:
        registered: false
        copyright: false
        care_of: false
  - pymdownx.superfences
  - pymdownx.tilde

#strict: true

copyright: Copyright &copy; 2020-2025 The oncvpsp Group
