#!/bin/sh
#edits various shell scripts to provide full path to executables

NEW_PREFIX=`pwd`

cp scripts/extract.sh scripts/replot.sh tests/

TMP=$$.tmp

sed -e /PREFIX=/s:PREFIX=.*$:PREFIX=$NEW_PREFIX: scripts/run.sh >$TMP
cp $TMP tests/run.sh
cp $TMP scripts/run.sh

sed -e /PREFIX=/s:PREFIX=.*$:PREFIX=$NEW_PREFIX: scripts/run_nr.sh >$TMP
cp $TMP tests/run_nr.sh
cp $TMP scripts/run_nr.sh

sed -e /PREFIX=/s:PREFIX=.*$:PREFIX=$NEW_PREFIX: scripts/run_r.sh >$TMP
cp $TMP tests/run_r.sh
cp $TMP scripts/run_r.sh

sed -e /PREFIX=/s:PREFIX=.*$:PREFIX=$NEW_PREFIX: scripts/run_nr.sh >$TMP
cp $TMP tests/multirun_nr.sh
cp $TMP scripts/run_nr.sh

sed -e /PREFIX=/s:PREFIX=.*$:PREFIX=$NEW_PREFIX: scripts/run_r.sh >$TMP
cp $TMP tests/multirun_r.sh
cp $TMP scripts/run_r.sh

sed -e /PREFIX=/s:PREFIX=.*$:PREFIX=$NEW_PREFIX: scripts/compare.sh >$TMP
cp $TMP tests/compare.sh
cp $TMP scripts/compare.sh

sed -e /PREFIX=/s:PREFIX=.*$:PREFIX=$NEW_PREFIX: scripts/compare_r.sh >$TMP
cp $TMP tests/compare_r.sh
cp $TMP scripts/compare_r.sh

chmod u+x tests/*sh

rm $TMP

